
insert into [UniQueDB].[dbo].[Persons] values (1, 'test', 'test', 1, 'Male', 'Sibling', 'No Special Reason', 'New emotions', 'Hight', 'Extrovert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (2, 'test', 'test', 2, 'Female', 'Relative', 'Mothers Day', 'Comics', 'Medium', 'Introvert', 'Kicks')
insert into [UniQueDB].[dbo].[Persons] values (3, 'test', 'test', 3, 'Male', 'Close Relative', 'Baby Birth', 'Solving Puzzle Games', 'Low', 'Extrovert', 'Play Station')
insert into [UniQueDB].[dbo].[Persons] values (4, 'test', 'test', 4, 'Female', 'Friend', 'Birthday', 'Running', 'Medium', 'Introvert', 'Book "Jungle in the Moomin-Troll Valley" by  Tove Jansson')
insert into [UniQueDB].[dbo].[Persons] values (5, 'test', 'test', 5, 'Male', 'Best Friend', 'Valentine''s Day', 'Art', 'Low', 'Extrovert', 'Znayking Developing Wood Mega Center')
insert into [UniQueDB].[dbo].[Persons] values (6, 'test', 'test', 10, 'Female', 'Colleague', 'Retirement', 'Fashion', 'Medium', 'Introvert', 'Baby LED shoes')
insert into [UniQueDB].[dbo].[Persons] values (7, 'test', 'test', 15, 'Male', 'Romantic Partner', 'Engagement', 'Sewing', 'Hight', 'Extrovert', 'Neon light pen')
insert into [UniQueDB].[dbo].[Persons] values (8, 'test', 'test', 20, 'Female', 'Parent', 'Birthday', 'Knitting', 'Low', 'Introvert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (9, 'test', 'test', 25, 'Male', 'Teacher', 'Christmas', 'Photography', 'Medium', 'Extrovert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (10, 'test', 'test', 30, 'Female', 'Child', 'Birthday', 'Solving Puzzle Games', 'Hight', 'Introvert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (11, 'test', 'test', 35, 'Male', 'Sibling', 'Year''s', 'Technology', 'Low', 'Extrovert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (12, 'test', 'test', 40, 'Female', 'Sibling', 'Wedding', 'Beauty', 'Medium', 'Introvert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (13, 'test', 'test', 45, 'Male', 'Relative', 'job or Promotion', 'Travel', 'Hight', 'Extrovert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (14, 'test', 'test', 50, 'Female', 'Close Relative', 'Birthday', 'Camping', 'Low', 'Introvert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (15, 'test', 'test', 55, 'Male', 'Friend', 'Birthday', 'Cooking', 'Medium', 'Extrovert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (16, 'test', 'test', 60, 'Female', 'Best Friend', 'Fathers Day', 'Yoga', 'Low', 'Introvert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (17, 'test', 'test', 65, 'Female', 'Colleague', 'Graduation', 'Board Games', 'Hight', 'Extrovert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (18, 'test', 'test', 70, 'Male', 'Romantic Partner', 'Birthday', 'Self Development', 'Medium', 'Introvert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (19, 'test', 'test', 75, 'Female', 'Parent', 'Wedding Anniversary', 'Reading Books', 'Low', 'Extrovert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (20, 'test', 'test', 80, 'Male', 'Teacher', 'Valentine''s Day', 'Films', 'Hight', 'Introvert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (21, 'test', 'test', 85, 'Female', 'Child', 'Fathers Day', 'Sport', 'Medium', 'Extrovert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (22, 'test', 'test', 90, 'Male', 'Sibling', 'Mothers Day', 'Football', 'Low', 'Introvert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (23, 'test', 'test', 95, 'Female', 'Relative', 'No Special Reason', 'Football', 'Hight', 'Extrovert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (24, 'test', 'test', 100, 'Male', 'Close Relative', 'Year''s', 'Football', 'Medium', 'Introvert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (25, 'test', 'test', 105, 'Female', 'Friend', 'Christmas', 'Football', 'Low', 'Introvert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (26, 'test', 'test', 110, 'Male', 'Best Friend', 'Wedding', 'Comics', 'Hight', 'Extrovert', 'Laptop')
insert into [UniQueDB].[dbo].[Persons] values (27, 'test', 'test', 115, 'Female', 'Colleague', 'Birthday', 'New emotions', 'Medium', 'Introvert', 'Laptop')
